### ISSUE TITLE
urllib3-!=1.25.0,!=1.25.1,<1.26,>=1.21.1'

### ISSUE THREAD

**Issue by mottosso** [mottosso/rez-pipz#1]
Rez doesn't support `!=` versions, we need to convert these to an equivalent Rez query.

Known affected packages:

- `requests`

**Comment by mottosso** [comment]
Also `docker`.

```bash
rez env pipz -- install docker
Using python-3.7
Using pip-19.1.1
Reading package lists... ok - 25.45s
Discovering existing packages... fail
...
rez.vendor.distlib.DistlibException: Ill-formed name/version string: 'ipaddress (>=1.0.16) ; python_version < "3.3)'
```

**Comment by mottosso** [comment]
And `twine`.

```bash
<rez> $ rez env pipz -- install twine
Using python-3.7
Using pip-19.1.1
Reading package lists... fail
Traceback (most recent call last):
  File "C:\Users\manima\packages\rez\2.32.1\python\rez\vendor\distlib\metadata.py", line 730, in __init__
    self._data = json.loads(data)
  File "C:\Users\manima\packages\python\3.7.3\platform-windows\arch-AMD64\app\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\manima\packages\python\3.7.3\platform-windows\arch-AMD64\app\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\manima\packages\python\3.7.3\platform-windows\arch-AMD64\app\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\manima\packages\python\3.7.3\platform-windows\arch-AMD64\app\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\manima\packages\python\3.7.3\platform-windows\arch-AMD64\app\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\manima\packages\pipz\1.0.6\python\pipz\__main__.py", line 3, in <module>
    exit(cli.main(sys.argv))
  File "C:\Users\manima\packages\pipz\1.0.6\python\pipz\cli.py", line 255, in main
    _install(opts, extra_args, tempdir)
  File "C:\Users\manima\packages\pipz\1.0.6\python\pipz\cli.py", line 91, in _install
    extra_args=extra_args,
  File "C:\Users\manima\packages\pipz\1.0.6\python\pipz\pip.py", line 173, in download
    distributions = list(distribution_path.get_distributions())
  File "C:\Users\manima\packages\rez\2.32.1\python\rez\vendor\distlib\database.py", line 213, in get_distributions
    self._generate_cache()
  File "C:\Users\manima\packages\rez\2.32.1\python\rez\vendor\distlib\database.py", line 167, in _generate_cache
    for dist in self._yield_distributions():
  File "C:\Users\manima\packages\rez\2.32.1\python\rez\vendor\distlib\database.py", line 148, in _yield_distributions
    metadata = Metadata(fileobj=stream, scheme='legacy')
  File "C:\Users\manima\packages\rez\2.32.1\python\rez\vendor\distlib\metadata.py", line 741, in __init__
    self.validate()
  File "C:\Users\manima\packages\rez\2.32.1\python\rez\vendor\distlib\metadata.py", line 958, in validate
    missing, warnings = self._legacy.check(True)
  File "C:\Users\manima\packages\rez\2.32.1\python\rez\vendor\distlib\metadata.py", line 522, in check
    self.set_metadata_version()
  File "C:\Users\manima\packages\rez\2.32.1\python\rez\vendor\distlib\metadata.py", line 289, in set_metadata_version
    self._fields['Metadata-Version'] = _best_version(self._fields)
  File "C:\Users\manima\packages\rez\2.32.1\python\rez\vendor\distlib\metadata.py", line 167, in _best_version
    raise MetadataConflictError('Unknown metadata set')
rez.vendor.distlib.metadata.MetadataConflictError: Unknown metadata set
```

**Comment by mottosso** [comment]
Also `montydb`.

```bash
rez.exceptions.PackageMetadataError: Validation of key 'requires' failed: Or(<class 'rez.utils.sourcecode.SourceCode'>, [And(<class 'str'>, Use(<class 'rez.utils.formatting.PackageRequest'>))]) did not validate ['attrs->=17.4.0', 'pyrsistent->=0.14.0', 'setuptools', 'six->=1.11.0', 'functools32 ; python_version < "3"']
Or(And(<class 'str'>, Use(<class 'rez.utils.formatting.PackageRequest'>))) did not validate 'functools32 ; python_version < "3"'
PackageRequest('functools32 ; python_version < "3"') raised VersionError('Syntax error in version range \'< "3"\': Syntax error in version range \'< "3"\'')
```

**Comment by mottosso** [comment]
And `imageio`.

```bash
rez env pipz -- install imageio
Using python-3.7
Using pip-19.1.1
Reading package lists... fail
Traceback (most recent call last):
  File "C:\Users\manima\packages\rez\2.33.3\platform-windows\arch-AMD64\os-windows-10\rez\vendor\distlib\metadata.py", line 730, in __init__
    self._data = json.loads(data)
  File "C:\Users\manima\packages\python\3.7.3\platform-windows\arch-AMD64\app\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\manima\packages\python\3.7.3\platform-windows\arch-AMD64\app\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\manima\packages\python\3.7.3\platform-windows\arch-AMD64\app\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\manima\packages\python\3.7.3\platform-windows\arch-AMD64\app\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\manima\packages\python\3.7.3\platform-windows\arch-AMD64\app\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\manima\packages\pipz\1.1.2\python\pipz\__main__.py", line 3, in <module>
    exit(cli.main(sys.argv))
  File "C:\Users\manima\packages\pipz\1.1.2\python\pipz\cli.py", line 263, in main
    _install(opts, extra_args, tempdir)
  File "C:\Users\manima\packages\pipz\1.1.2\python\pipz\cli.py", line 91, in _install
    extra_args=extra_args,
  File "C:\Users\manima\packages\pipz\1.1.2\python\pipz\pip.py", line 174, in download
    distributions = list(distribution_path.get_distributions())
  File "C:\Users\manima\packages\rez\2.33.3\platform-windows\arch-AMD64\os-windows-10\rez\vendor\distlib\database.py", line 213, in get_distributions
    self._generate_cache()
  File "C:\Users\manima\packages\rez\2.33.3\platform-windows\arch-AMD64\os-windows-10\rez\vendor\distlib\database.py", line 167, in _generate_cache
    for dist in self._yield_distributions():
  File "C:\Users\manima\packages\rez\2.33.3\platform-windows\arch-AMD64\os-windows-10\rez\vendor\distlib\database.py", line 148, in _yield_distributions
    metadata = Metadata(fileobj=stream, scheme='legacy')
  File "C:\Users\manima\packages\rez\2.33.3\platform-windows\arch-AMD64\os-windows-10\rez\vendor\distlib\metadata.py", line 741, in __init__
    self.validate()
  File "C:\Users\manima\packages\rez\2.33.3\platform-windows\arch-AMD64\os-windows-10\rez\vendor\distlib\metadata.py", line 958, in validate
    missing, warnings = self._legacy.check(True)
  File "C:\Users\manima\packages\rez\2.33.3\platform-windows\arch-AMD64\os-windows-10\rez\vendor\distlib\metadata.py", line 522, in check
    self.set_metadata_version()
  File "C:\Users\manima\packages\rez\2.33.3\platform-windows\arch-AMD64\os-windows-10\rez\vendor\distlib\metadata.py", line 289, in set_metadata_version
    self._fields['Metadata-Version'] = _best_version(self._fields)
  File "C:\Users\manima\packages\rez\2.33.3\platform-windows\arch-AMD64\os-windows-10\rez\vendor\distlib\metadata.py", line 167, in _best_version
    raise MetadataConflictError('Unknown metadata set')
rez.vendor.distlib.metadata.MetadataConflictError: Unknown metadata set
```

**Comment by mottosso** [comment]
With #21, some of these were fixes.

- `montydb` was fully resolved (yay!)
- `twine` was partly resolved, now having the `Unknown metadata set` issue instead
- `docker` was partly resolved, however it also uses `!!name` for its requirements which are also not supported. (I don't know what they mean, and haven't located any docs for them)

```bash
rez.exceptions.PackageMetadataError: Validation of key 'requires' failed: Or(<class 'rez.utils.sourcecode.SourceCode'>, [And(<class 'str'>, Use(<class 'rez.utils.formatting.PackageRequest'>))]) did not validate ['idna<2.9', 'idna>=2.5', 'certifi>=2017.4.17', 'chardet<3.1.0', 'chardet>=3.0.2', '!urllib31.25.0', '!!urllib31.25.1', '!!urllib3<1.26', '!!urllib3>=1.21.1']
Or(And(<class 'str'>, Use(<class 'rez.utils.formatting.PackageRequest'>))) did not validate '!!urllib31.25.1'
PackageRequest('!!urllib31.25.1') raised PackageRequestError("Not a valid package name: '!urllib31.25.1'")
````
